# Author: truocphan
# Date: 22.04.2023
version: "3.9"
services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD = dbrootpassword
      - MYSQL_DATABASE = wordpress
      - MYSQL_USER = dbusername
      - MYSQL_PASSWORD = dbpassword
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:6.2
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - wordpress_data:/var/www/html
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    restart: always
    environment:
      - WORDPRESS_DB_HOST = db
      - WORDPRESS_DB_USER = dbusername
      - WORDPRESS_DB_PASSWORD = dbpassword
      - WORDPRESS_DB_NAME = wordpress
volumes:
  db_data:
  wordpress_data:
